# fly.toml file generated for mercadocontrolback on 2023-04-04T11:26:27-05:00

app = "mercadocontrolback"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bog"

[env]
  PORT = "8000"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
