# Generated by Django 3.2.18 on 2023-04-02 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe tener entre 10 y 15 dígitos.', regex='^\\d{10,15}$')], verbose_name='número de celular')),
                ('indicative', models.CharField(blank=True, max_length=10, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección de contacto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
