# Generated by Django 3.2.18 on 2023-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='número de celular'),
        ),
    ]
