# Generated by Django 3.2.18 on 2023-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0002_alter_supermarket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='logo_supermarket',
            field=models.ImageField(blank=True, null=True, upload_to='logo_supermarket/'),
        ),
    ]
