# Generated by Django 3.2.18 on 2023-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VERDURAS', 'VERDURAS'), ('CARNE', 'CARNE'), ('ASEO', 'ASEO'), ('ALACENA', 'ALACENA')], max_length=100),
        ),
    ]
