# Generated by Django 3.2.18 on 2023-04-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
