# Generated by Django 3.2.18 on 2023-04-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_prices', '0001_initial'),
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_list',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='estimated_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='list_of_prices',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_prices_shopping_list', to='list_of_prices.list_of_price'),
            preserve_default=False,
        ),
    ]
