# Generated by Django 3.2.18 on 2023-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_prices', '0002_list_of_price_shopping_lists'),
        ('shopping_lists', '0002_auto_20230405_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list',
            name='list_of_prices',
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='list_of_prices',
            field=models.ManyToManyField(related_name='list_of_prices', to='list_of_prices.List_of_price'),
        ),
    ]
