# Generated by Django 3.2.18 on 2023-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_prices', '0006_auto_20230410_1034'),
        ('shopping_lists', '0006_remove_shopping_list_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list',
            name='list_of_prices',
        ),
        migrations.CreateModel(
            name='ShoppingListListofPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('added', models.BooleanField(default=False)),
                ('list_of_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_prices.list_of_price')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_lists.shopping_list')),
            ],
        ),
    ]
