# Generated by Django 3.2.18 on 2023-04-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0004_auto_20230408_0955'),
        ('list_of_prices', '0002_list_of_price_shopping_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_price',
            name='shopping_lists',
        ),
        migrations.CreateModel(
            name='ShoppingListListofPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.IntegerField()),
                ('added', models.BooleanField(default=False)),
                ('list_of_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_prices.list_of_price')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_lists.shopping_list')),
            ],
        ),
    ]
