# Generated by Django 3.2.18 on 2023-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0004_auto_20230408_0955'),
        ('list_of_prices', '0003_auto_20230408_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_price',
            name='shopping_lists',
            field=models.ManyToManyField(related_name='shopping_lists', through='list_of_prices.ShoppingListListofPrice', to='shopping_lists.Shopping_list'),
        ),
    ]
