# Generated by Django 3.2.18 on 2023-04-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0007_auto_20230410_1034'),
        ('list_of_prices', '0006_auto_20230410_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingListListofPrice',
        ),
    ]
