# Generated by Django 3.2.18 on 2023-04-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('list_of_prices', '0007_delete_shoppinglistlistofprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_price',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
            preserve_default=False,
        ),
    ]
