# Generated by Django 3.2.18 on 2023-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_prices', '0008_list_of_price_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_price',
            name='aditional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
