# Generated by Django 3.2.18 on 2023-04-02 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección de contacto'),
        ),
        migrations.AddField(
            model_name='user',
            name='indicativo_telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe tener entre 10 y 15 dígitos.', regex='^\\d{10,15}$')], verbose_name='número de celular'),
        ),
    ]
