# Generated by Django 3.2.18 on 2023-04-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230402_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='currency',
            new_name='currency_unit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='indicativo_telefono',
            new_name='indicative',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
    ]
